trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:

# Visual Studio Test
# Run unit and functional tests (Selenium, Appium, Coded UI test, etc.) using the Visual Studio Test (VsTest) runner.
# Test frameworks that have a Visual Studio test adapter such as MsTest, xUnit, NUnit, Chutzpah (for JavaScript tests using QUnit, Mocha and Jasmine), etc. can be run.
# Tests can be distributed on multiple agents using this task (version 2).
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\*test*.dll'
    searchFolder: '$(System.DefaultWorkingDirectory)'
